import mongoose, { Document, Schema } from 'mongoose';

/**
 * Every kind of notification the platform can raise.
 *
 * The first block is event-driven (something another person did); the
 * "reminder" block is generated by `reminderService`, which looks at what a
 * shopper already did — carts left behind, wishlisted items, past orders —
 * and nudges them at the right moment.
 */
export const NOTIFICATION_TYPES = [
  // Social / transactional events
  'like',
  'comment',
  'follow',
  'order_update',
  'message',
  'mention',
  'repost',
  'community',
  'promotion',
  'offer',
  'subscription_limit',
  'product_added',
  'verification',
  'moderation',
  // Reminders (see services/reminderService.ts)
  'cart_reminder',
  'wishlist_price_drop',
  'back_in_stock',
  'review_reminder',
  'reorder_reminder',
  'delivery_reminder',
  'recommendation',
] as const;

export type NotificationType = typeof NOTIFICATION_TYPES[number];

export interface INotification extends Document {
  _id: mongoose.Types.ObjectId;
  recipient_username: string;
  type: NotificationType;
  title: string;
  body?: string;
  link?: string;
  sender_username?: string;
  sender_name?: string;
  is_read: boolean;
  metadata?: Record<string, any>;
  /**
   * Idempotency key for generated reminders — "this exact nudge, for this
   * recipient". A second attempt with the same key is dropped instead of
   * pushing a duplicate to the device, which is what keeps a sweep that runs
   * every 30 minutes from re-sending yesterday's reminder.
   */
  dedupe_key?: string;
  created_at: Date;
  updated_at: Date;
}

const NotificationSchema = new Schema<INotification>({
  recipient_username: {
    type: String,
    required: true,
    lowercase: true,
    trim: true,
    index: true,
  },
  type: {
    type: String,
    required: true,
    enum: NOTIFICATION_TYPES,
  },
  title: {
    type: String,
    required: true,
    trim: true,
  },
  body: {
    type: String,
    trim: true,
  },
  link: {
    type: String,
  },
  sender_username: {
    type: String,
    lowercase: true,
    trim: true,
  },
  sender_name: {
    type: String,
    trim: true,
  },
  is_read: {
    type: Boolean,
    default: false,
  },
  metadata: {
    type: Schema.Types.Mixed,
  },
  dedupe_key: {
    type: String,
    trim: true,
  },
}, {
  timestamps: {
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
});

// Indexes for performance
NotificationSchema.index({ recipient_username: 1, created_at: -1 });
NotificationSchema.index({ recipient_username: 1, is_read: 1 });
NotificationSchema.index({ type: 1 });
NotificationSchema.index({ sender_username: 1 });
NotificationSchema.index({ created_at: 1 }, { expireAfterSeconds: 7_776_000 }); // TTL: 90 days

// Partial (not sparse) so the uniqueness only applies to documents that
// actually carry a dedupe key — a compound sparse index would still cover
// every document, since recipient_username is always present.
NotificationSchema.index(
  { recipient_username: 1, dedupe_key: 1 },
  { unique: true, partialFilterExpression: { dedupe_key: { $exists: true } } }
);

export const Notification = mongoose.model<INotification>('Notification', NotificationSchema);
